Add all formatter from bazel

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -35,6 +35,10 @@ jobs:
         run: bazel run //js/checkers -- --root_dir "${{ github.workspace }}"
       - name: Github Action Linter
         run: bazel run @multitool//tools/actionlint:cwd -- -config-file "${{ github.workspace }}/.github/actionlint.yaml"
+      - name: Code formatting
+        run: |
+          bazel run //:format
+          if [[ $(git status --porcelain) ]]; then echo "**** run 'bazel run //:format' to fix formatting errors"; exit 1; fi
   js-checks:
     runs-on: ubuntu-24.04
     steps:
